### ISSUE TITLE
Uncaught Error: cannot call methods on slider prior to initialization; attempted to call method 'option' 

### ISSUE THREAD

**Issue by drwmrrs** [virtuozzo/OnApp-WHMCS-Module#2]
Hi Guys,

Receiving the following error when configuring an OnApp product (where you select memory, cpus etc):

`Uncaught Error: cannot call methods on slider prior to initialization; attempted to call method 'option'` 

I believe the sliders are not being rendered or not operating properly due to this issue, they are also returning strange values, i.e. if I put '1' in the swap value, the input value then becomes '1,2'

Any ideas on this?

**Comment by drwmrrs** [comment]
Hi, any updates on this?

**Comment by vijinmv** [comment]
Hello guys,

I am also getting same error. I started getting this error after the WHMCS version upgrade and previously there was no issue with the slider. Please have solution for this issue. I am dam sure that the issue is related with the onapp module version compatibility with WHMCS 5.2.7 version.

Best Regards,
Vijin M Vijayan

**Comment by yatskovets** [comment]
WHMCS changed jquery slider library.
We cant support all versions.
Please download last version we have support last WHMCS there.

Thanks.
